version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    container_name: data-stream-server
    ports:
      - "50051:50051"
    env_file: .env
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: ./cmd/client/Dockerfile
    container_name: data-stream-client
    env_file: .env
    depends_on:
      - server

  db:
    image: postgres:13
    container_name: postgres-db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
